#!/usr/bin/env python3
"""T1.10 -- cold-beam finite-grid instability at the MR seam.

Stanier et al. 2019 (JCP 376:597) Sec. 5-style setup plus a static
refinement patch: a COLD plasma drifting along B0 (u = v0 z_hat, B0 z_hat)
in a periodic quasi-1D 2D domain.  In the plasma frame nothing happens;
on the mesh the drift breaks Galilean invariance and the aliased beam
modes omega = (k - p k_grid) v0 couple to the whistler branch -> the
finite-grid (drift-resonant) instability grows from PIC noise at
grid-scale k.  A field-aligned drift carries no motional E and no free
energy, so ANY growth is numerical -- exactly the channel under test.

Grid/harness follow the T1 conventions (t1_whistler.py): coarse
4 x 512 cells (dz = 0.5 l_i, Lz = 256 l_i), static full-x ratio-2 patch
over the middle quarter of z (seams at 96 and 160 l_i); uniform-fine
control is 8 x 1024 at max_level 0.  Physics base identical (B0 = 0.25 T,
m_i = 100 m_e, vA/c = 1e-4) but COLD: beta_i = beta_e = 1e-3 by default
(v_ti = 0.022 vA << v0).

Resistivity DAMPS the instability under test, so the default eta is the
bare deck value 1e-10 Ohm m and the horizon is bounded to the
instability's own timescale; eta = 1e-7 arms exist only as a control leg
to show the floor suppresses the instability symmetrically in MR and
uniform arms.

Example:
  python t1_10_beam.py --name t110_ctl --max-level 0 --v0-fac 2.0 \
      --steps 2500 --out t1_runs/t110_ctl --nprocs 16
"""

import argparse
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from t1_whistler import (  # noqa: E402  (shared physics, identical by import)
    B0,
    M_ION,
    c_light,
    l_i,
    n0,
    run_warpx,
    t_ci,
    vA,
    w_ci,
)

# ----------------------------------------------------------------------
# grid: coarse dz = 0.5 l_i, Lz = 256 l_i, quasi-1D (thin periodic x)
# ----------------------------------------------------------------------
DZ_COARSE_LI = 0.5
NZ_COARSE = 512
NX_COARSE = 4
dz_c = DZ_COARSE_LI * l_i
Lz = NZ_COARSE * dz_c
Lx = NX_COARSE * dz_c
k_Nyq_coarse = np.pi / dz_c

PATCH_ZLO_FAC, PATCH_ZHI_FAC = 0.375, 0.625  # seams at 96 and 160 l_i

BETA_I = 1.0e-3  # cold beam
BETA_E = 1.0e-3

INPUTS_TEMPLATE = """# auto-generated by t1_10_beam.py -- do not edit ({case_name})
max_step = {steps}
warpx.const_dt = {dt:.10e}
warpx.verbose = 1

amr.n_cell = {nx} {nz}
amr.max_level = {max_level}
amr.blocking_factor = 4
amr.max_grid_size = {max_grid_size}
amr.n_error_buf = 0
{fine_tag_block}
geometry.dims = 2
geometry.prob_lo = {xlo:.10e} 0.0
geometry.prob_hi = {xhi:.10e} {Lz:.10e}

boundary.field_lo = periodic periodic
boundary.field_hi = periodic periodic
boundary.particle_lo = periodic periodic
boundary.particle_hi = periodic periodic

algo.maxwell_solver = hybrid
algo.current_deposition = direct
algo.particle_shape = 1

hybrid_pic_model.elec_temp = {Te:.10e}
hybrid_pic_model.gamma = 1.0
hybrid_pic_model.n0_ref = {n0:.10e}
hybrid_pic_model.plasma_resistivity(rho,J,t) = {eta}
hybrid_pic_model.plasma_hyper_resistivity(rho,B) = 0.0
hybrid_pic_model.substeps = {substeps}

warpx.B_ext_grid_init_style = parse_b_ext_grid_function
warpx.Bx_external_grid_function(x,y,z) = "0.0"
warpx.By_external_grid_function(x,y,z) = "0.0"
warpx.Bz_external_grid_function(x,y,z) = "{B0:.10e}"

particles.species_names = ions
ions.charge = q_e
ions.mass = {M_ion:.10e}
ions.injection_style = nrandompercell
ions.num_particles_per_cell = {ppc}
ions.profile = constant
ions.density = {n0:.10e}
ions.momentum_distribution_type = gaussian
ions.uz_m = {u_drift:.10e}
ions.ux_th = {uth:.10e}
ions.uy_th = {uth:.10e}
ions.uz_th = {uth:.10e}

diagnostics.diags_names = diag1
diag1.diag_type = Full
diag1.format = plotfile
diag1.intervals = {plot_int}
diag1.fields_to_plot = Bx By Bz Ex Ey Ez
diag1.write_species = 0

warpx.reduced_diags_names = field_energy
field_energy.type = FieldEnergy
field_energy.intervals = 5

warpx.serialize_initial_conditions = 1
"""


def build_case(args):
    if args.resolution == "coarse":
        nx, nz = NX_COARSE, NZ_COARSE
    else:  # uniform-fine control: dz = 0.25 l_i everywhere
        nx, nz = 2 * NX_COARSE, 2 * NZ_COARSE
        assert args.max_level == 0, "fine resolution is a max_level=0 control"
    dx = Lx / nx

    v0 = args.v0_fac * vA
    v_ti = np.sqrt(BETA_I / 2.0) * vA
    Te_eV = M_ION * (BETA_E / 2.0) * vA**2 / 1.602176634e-19

    if args.max_level > 0:
        xtlo, xthi = -0.5 * Lx - dx, +0.5 * Lx + dx  # full-x patch
        fine_tag_block = (
            f"warpx.fine_tag_lo = {xtlo:.10e} {PATCH_ZLO_FAC * Lz:.10e}\n"
            f"warpx.fine_tag_hi = {xthi:.10e} {PATCH_ZHI_FAC * Lz:.10e}\n"
            "warpx.refine_plasma_init = 1\n"
        )
    else:
        fine_tag_block = ""

    dt = args.dt_fac * t_ci
    # cells crossed per step (finite-grid-instability control parameter)
    adv_c = v0 * dt / dz_c
    adv_f = 2.0 * adv_c

    case = dict(
        case_name=args.name,
        steps=args.steps,
        dt=dt,
        dt_fac=args.dt_fac,
        nx=nx,
        nz=nz,
        max_grid_size=args.max_grid_size,
        max_level=args.max_level,
        resolution=args.resolution,
        xlo=-0.5 * Lx,
        xhi=+0.5 * Lx,
        Lz=Lz,
        Lx=Lx,
        fine_tag_block=fine_tag_block,
        Te=Te_eV,
        n0=n0,
        eta=args.eta,
        substeps=args.substeps,
        B0=B0,
        M_ion=M_ION,
        ppc=args.ppc,
        uth=v_ti / c_light,
        u_drift=v0 / c_light,
        plot_int=args.plot_int,
        # bookkeeping for the analysis
        mode="coldbeam",
        v0=v0,
        v0_fac=args.v0_fac,
        beta_i=BETA_I,
        beta_e=BETA_E,
        v_ti_va=v_ti / vA,
        adv_cells_coarse=adv_c,
        adv_cells_fine=adv_f,
        patch_zlo=PATCH_ZLO_FAC * Lz,
        patch_zhi=PATCH_ZHI_FAC * Lz,
        w_ci=w_ci,
        t_ci=t_ci,
        l_i=l_i,
        vA=vA,
        k_nyq_coarse=k_Nyq_coarse,
        dz_coarse=dz_c,
        extra_inputs=args.extra_inputs,
    )
    return case


def write_run(case, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    inputs_path = os.path.join(out_dir, "inputs_t1")
    with open(inputs_path, "w") as f:
        f.write(INPUTS_TEMPLATE.format(**case))
        for line in case.get("extra_inputs") or []:
            f.write(line + "\n")
    with open(os.path.join(out_dir, "params.json"), "w") as f:
        json.dump(
            {k: v for k, v in case.items() if not k.endswith("_block")},
            f,
            indent=1,
            default=float,
        )
    return inputs_path


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--name", default="t110_run")
    p.add_argument("--max-level", type=int, default=1, choices=[0, 1])
    p.add_argument("--resolution", choices=["coarse", "fine"], default="coarse")
    p.add_argument("--v0-fac", type=float, default=2.0, help="drift v0 / vA")
    p.add_argument("--eta", default="1.0e-10", help="plasma_resistivity (Ohm m)")
    p.add_argument("--substeps", type=int, default=24)
    p.add_argument("--max-grid-size", type=int, default=32)
    p.add_argument("--extra-inputs", action="append", default=None)
    p.add_argument("--ppc", type=int, default=64)
    p.add_argument("--dt-fac", type=float, default=0.012, help="dt / t_ci")
    p.add_argument("--steps", type=int, default=2500)
    p.add_argument("--plot-int", type=int, default=5)
    p.add_argument("--out", required=True)
    p.add_argument("--exe", default=None)
    p.add_argument("--nprocs", type=int, default=16)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    if args.exe is None:
        args.exe = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "..",
            "..",
            "..",
            "build",
            "bin",
            "warpx.2d",
        )

    case = build_case(args)
    write_run(case, args.out)
    print(
        f"[t1_10_beam] {args.name}: v0 = {args.v0_fac:g} vA "
        f"(v_ti = {case['v_ti_va']:.4f} vA, beta_i = {BETA_I:g}), "
        f"drift = {case['adv_cells_coarse']:.3f} coarse / "
        f"{case['adv_cells_fine']:.3f} fine cells per step, "
        f"horizon = {args.steps * args.dt_fac:.1f} t_ci, eta = {args.eta}"
    )
    if case["adv_cells_fine"] > 1.0:
        print("[t1_10_beam] WARNING: >1 fine cell per step -- CFL violated")
    if args.dry_run:
        return 0
    rc = run_warpx(case, args.out, args.exe, args.nprocs)
    if rc != 0:
        print(f"[t1_10_beam] WARNING: {args.name} exited with code {rc}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
