#!/usr/bin/env python3
"""T1.3 -- Alfven-wave patch-transit deck for hybrid-PIC mesh refinement.

PHARE + LatHyS design (11-transit phase-error tracking): a low-k Alfvenic
wave (k l_i << 1, whistler/R branch, omega ~ k vA) propagates along z in a
periodic quasi-1D 2D domain and repeatedly crosses a static ratio-2
refinement patch spanning the full (thin) x extent and the middle quarter
of z. Physics identical to t1_whistler.py (beta = 1, B0 = 0.25 T along z,
m_i = 100 m_e, vA/c = 1e-4); the domain is 4 x 256 coarse cells
(dz = 0.5 l_i, Lz = 128 l_i) so one domain transit = one patch crossing =
19.9 t_ci and 11 transits fit in ~219 t_ci.

Unlike t1_whistler.py the wave is launched PROPAGATING: the B-only IC
splits into equal counter-propagating Alfven waves at low k (standing
wave), so ions get the Walen velocity perturbation

    du = -(vA^2 / v_ph) dB / B0,   v_ph = omega_R(k)/k

via the `maxwellian` momentum distribution with parsed mean. The residual
counter-propagating admixture from kinetic/dispersive mismatch is ~1-2%
and identical in all arms (shared-seed convention).

Resistive damping of the wave at the stabilized-arm floor
eta = 3e-8 Ohm m: gamma_eta = eta k^2 / mu0 = 2.8e-8 w_ci, i.e.
gamma_eta * (11 transits) ~ 4e-5 -- negligible by construction.

Example:
  python t1_3_alfven.py --name t13_mr_stab --max-level 1 --eta 3.0e-8 \
      --dt-fac 0.012 --steps 18700 --plot-int 20 --out t1_runs/t13_mr_stab
"""

import argparse
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from t1_whistler import (  # noqa: E402  (shared physics, identical by import)
    AMP_FAC,
    B0,
    BETA,
    ETA_H_STAR,
    M_ION,
    Te_eV,
    c_light,
    l_i,
    n0,
    run_warpx,
    t_ci,
    u_th,
    vA,
    w_ci,
)

# ----------------------------------------------------------------------
# grid: coarse dz = 0.5 l_i as in T1.1, but a 4x SHORTER domain so that
# 11 patch transits are affordable (transit time = Lz / v_ph)
# ----------------------------------------------------------------------
DZ_COARSE_LI = 0.5
NZ_COARSE = 256
NX_COARSE = 4
dz_c = DZ_COARSE_LI * l_i
Lz = NZ_COARSE * dz_c  # = 128 l_i
Lx = NX_COARSE * dz_c  # = 2 l_i
k_Nyq_coarse = np.pi / dz_c

PATCH_ZLO_FAC, PATCH_ZHI_FAC = 0.375, 0.625  # seams at 48 and 80 l_i

INPUTS_TEMPLATE = """# auto-generated by t1_3_alfven.py -- do not edit ({case_name})
max_step = {steps}
warpx.const_dt = {dt:.10e}
warpx.verbose = 1

amr.n_cell = {nx} {nz}
amr.max_level = {max_level}
amr.blocking_factor = 4
amr.max_grid_size = {max_grid_size}
amr.n_error_buf = 0
{fine_tag_block}
geometry.dims = 2
geometry.prob_lo = {xlo:.10e} 0.0
geometry.prob_hi = {xhi:.10e} {Lz:.10e}

boundary.field_lo = periodic periodic
boundary.field_hi = periodic periodic
boundary.particle_lo = periodic periodic
boundary.particle_hi = periodic periodic

algo.maxwell_solver = hybrid
algo.current_deposition = direct
algo.particle_shape = 1

hybrid_pic_model.elec_temp = {Te:.10e}
hybrid_pic_model.gamma = 1.0
hybrid_pic_model.n0_ref = {n0:.10e}
hybrid_pic_model.plasma_resistivity(rho,J,t) = {eta}
hybrid_pic_model.plasma_hyper_resistivity(rho,B) = {eta_h}
hybrid_pic_model.substeps = {substeps}

# initial B: uniform B0 z + right-hand circular perturbation (div-free)
warpx.B_ext_grid_init_style = parse_b_ext_grid_function
warpx.Bx_external_grid_function(x,y,z) = "{bx_expr}"
warpx.By_external_grid_function(x,y,z) = "{by_expr}"
warpx.Bz_external_grid_function(x,y,z) = "{B0:.10e}"

particles.species_names = ions
ions.charge = q_e
ions.mass = {M_ion:.10e}
ions.injection_style = nrandompercell
ions.num_particles_per_cell = {ppc}
ions.profile = constant
ions.density = {n0:.10e}
# Walen-matched propagating Alfven wave: du = -(vA^2/v_ph) dB/B0
ions.momentum_distribution_type = maxwellian
ions.maxwellian_u_mean_distribution_type = parser
ions.ux_mean_function(x,y,z) = "{ux_expr}"
ions.uy_mean_function(x,y,z) = "{uy_expr}"
ions.uz_mean_function(x,y,z) = "0.0"
ions.maxwellian_u_std_distribution_type = constant
ions.ux_std = {uth:.10e}
ions.uy_std = {uth:.10e}
ions.uz_std = {uth:.10e}

diagnostics.diags_names = diag1
diag1.diag_type = Full
diag1.format = plotfile
diag1.intervals = {plot_int}
diag1.fields_to_plot = Bx By Bz Ex Ey Ez
diag1.write_species = 0

warpx.reduced_diags_names = field_energy
field_energy.type = FieldEnergy
field_energy.intervals = 10

warpx.serialize_initial_conditions = 1
"""


def whistler_omega(k):
    """Cold hybrid R-mode (whistler/Alfven branch), continuum."""
    kn = k * l_i
    return w_ci * 0.5 * (kn**2 + kn * np.sqrt(kn**2 + 4.0))


def build_case(args):
    m = args.m_index
    k = 2.0 * np.pi * m / Lz
    om = whistler_omega(k)
    vph = om / k
    T_transit = Lz / vph

    if args.resolution == "coarse":
        nx, nz = NX_COARSE, NZ_COARSE
    else:  # uniform-fine reference, dz = 0.25 l_i everywhere
        nx, nz = 2 * NX_COARSE, 2 * NZ_COARSE
        assert args.max_level == 0, "fine resolution is a max_level=0 reference"
    dx = Lx / nx

    A = args.amp_fac * B0
    bx_expr = f"{A:.10e}*cos({k:.10e}*z)"
    by_expr = f"-{A:.10e}*sin({k:.10e}*z)"
    # normalized (u = gamma v/c ~ v/c) Walen mean-velocity amplitude
    u_amp = args.amp_fac * (vA / c_light) * (vA / vph)
    ux_expr = f"-{u_amp:.10e}*cos({k:.10e}*z)"
    uy_expr = f"{u_amp:.10e}*sin({k:.10e}*z)"

    if args.max_level > 0:
        xtlo, xthi = -0.5 * Lx - dx, +0.5 * Lx + dx  # full-x patch
        fine_tag_block = (
            f"warpx.fine_tag_lo = {xtlo:.10e} {PATCH_ZLO_FAC * Lz:.10e}\n"
            f"warpx.fine_tag_hi = {xthi:.10e} {PATCH_ZHI_FAC * Lz:.10e}\n"
        )
    else:
        fine_tag_block = ""

    dt = args.dt_fac * t_ci
    eta_h = args.eta_h_fac * ETA_H_STAR
    eta_num = float(args.eta)
    gamma_eta = eta_num * k**2 / (4.0e-7 * np.pi)

    case = dict(
        case_name=args.name,
        steps=args.steps,
        dt=dt,
        dt_fac=args.dt_fac,
        nx=nx,
        nz=nz,
        max_grid_size=args.max_grid_size,
        max_level=args.max_level,
        resolution=args.resolution,
        xlo=-0.5 * Lx,
        xhi=+0.5 * Lx,
        Lz=Lz,
        Lx=Lx,
        fine_tag_block=fine_tag_block,
        Te=Te_eV,
        n0=n0,
        eta=args.eta,
        eta_h=f"{eta_h:.10e}" if args.eta_h_fac > 0 else "0.0",
        eta_h_fac=args.eta_h_fac,
        substeps=args.substeps,
        B0=B0,
        bx_expr=bx_expr,
        by_expr=by_expr,
        ux_expr=ux_expr,
        uy_expr=uy_expr,
        u_amp=u_amp,
        M_ion=M_ION,
        ppc=args.ppc,
        uth=u_th,
        plot_int=args.plot_int,
        # bookkeeping for the analysis
        mode="alfven",
        m_index=m,
        k_si=k,
        kfac=k / k_Nyq_coarse,
        amp=A,
        amp_fac=args.amp_fac,
        om_theory=om,
        vph=vph,
        T_transit=T_transit,
        T_transit_tci=T_transit / t_ci,
        gamma_eta=gamma_eta,
        gamma_eta_wci=gamma_eta / w_ci,
        patch_zlo=PATCH_ZLO_FAC * Lz,
        patch_zhi=PATCH_ZHI_FAC * Lz,
        w_ci=w_ci,
        t_ci=t_ci,
        l_i=l_i,
        vA=vA,
        k_nyq_coarse=k_Nyq_coarse,
        beta=BETA,
        dz_coarse=dz_c,
        extra_inputs=args.extra_inputs,
    )
    return case


def write_run(case, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    # named inputs_t1 because t1_whistler.run_warpx hardcodes that filename
    inputs_path = os.path.join(out_dir, "inputs_t1")
    with open(inputs_path, "w") as f:
        f.write(INPUTS_TEMPLATE.format(**case))
        for line in case.get("extra_inputs") or []:
            f.write(line + "\n")
    with open(os.path.join(out_dir, "params.json"), "w") as f:
        json.dump(
            {k: v for k, v in case.items() if not k.endswith("_block")},
            f,
            indent=1,
            default=float,
        )
    return inputs_path


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--name", default="t13_run")
    p.add_argument("--m-index", type=int, default=1, help="wave harmonic (k=2 pi m/Lz)")
    p.add_argument("--max-level", type=int, default=1, choices=[0, 1])
    p.add_argument("--resolution", choices=["coarse", "fine"], default="coarse")
    p.add_argument("--eta", default="1.0e-10", help="plasma_resistivity (Ohm m)")
    p.add_argument("--eta-h-fac", type=float, default=0.0)
    p.add_argument("--amp-fac", type=float, default=AMP_FAC)
    p.add_argument("--substeps", type=int, default=24)
    p.add_argument("--max-grid-size", type=int, default=32)
    p.add_argument("--extra-inputs", action="append", default=None)
    p.add_argument("--ppc", type=int, default=64)
    p.add_argument("--dt-fac", type=float, default=0.012, help="dt / t_ci")
    p.add_argument("--steps", type=int, default=18700)
    p.add_argument("--plot-int", type=int, default=20)
    p.add_argument("--out", required=True)
    p.add_argument("--exe", default=None)
    p.add_argument("--nprocs", type=int, default=8)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    if args.exe is None:
        args.exe = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "..",
            "..",
            "..",
            "build",
            "bin",
            "warpx.2d",
        )

    case = build_case(args)
    write_run(case, args.out)
    print(
        f"[t1_3_alfven] {args.name}: m={case['m_index']} "
        f"(k l_i = {case['k_si'] * l_i:.4f}, {case['kfac']:.4f} k_Nc), "
        f"omega_R = {case['om_theory'] / w_ci:.4f} w_ci, "
        f"v_ph = {case['vph'] / vA:.4f} vA, "
        f"transit = {case['T_transit_tci']:.2f} t_ci; "
        f"horizon = {args.steps * args.dt_fac / case['T_transit_tci']:.2f} transits"
    )
    print(
        f"[t1_3_alfven] eta = {args.eta} Ohm m -> gamma_eta = "
        f"{case['gamma_eta_wci']:.2e} w_ci "
        f"(gamma_eta * horizon = {case['gamma_eta'] * args.steps * case['dt']:.2e})"
    )
    if args.dry_run:
        return 0
    rc = run_warpx(case, args.out, args.exe, args.nprocs)
    if rc != 0:
        print(f"[t1_3_alfven] WARNING: {args.name} exited with code {rc}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
