#!/usr/bin/env python3
"""T1.4 -- advected tangential discontinuity through the MR seam (PHARE
benchmark) for hybrid-PIC mesh refinement.

Quasi-1D 2D domain (thin periodic x, long periodic z), coarse 4 x 512
cells (dz = 0.5 l_i, Lz = 256 l_i), static ratio-2 patch over the middle
quarter of z (seams at 96 and 160 l_i). The tangential discontinuity is a
rotation of B in the plane PERPENDICULAR to the gradient (B_z = 0, so
B.n = 0 as a TD requires and div B = 0 exactly on the Yee mesh):

    theta(z) = (dtheta/2) [tanh((z-za)/L) - tanh((z-zb)/L)]
    Bx = B0 cos(theta),  By = B0 sin(theta),  Bz = 0

|B| = B0 = const and n, T uniform, so total pressure is constant. Because
|B| is constant the Hall term J x B ~ -grad(B^2/2)/mu0 vanishes
identically: the exact GOL solution is the pure motional field
E = -u x B with E_z = 0, and the structure advects with the uniform bulk
drift u_z. E_z and B_z are therefore true should-be-zero artifact
monitors (MHD-EPIC detector). The layer current is carried by the
electron fluid; ions are a drifting Maxwellian.

Default geometry: za = 64 l_i, zb = 88 l_i (24 l_i slab), L = 1.5 l_i
(3 coarse cells -- a deliberately sharp layer to stress the unlimited
FaceDivFree transverse slopes), drift u_z = 1.0 vA. Leading layer hits
the upstream seam at 1.3 t_ci (inside the bare-seam valid window), the
slab is fully inside the patch from 5.1 to 11.5 t_ci and fully out by
15.3 t_ci; at the default 1900 steps (22.8 t_ci) the slab has drifted
143 l_i and nothing has wrapped around the periodic boundary.

Example:
  python t1_4_td.py --name t14_mr --max-level 1 --eta 3.0e-8 \
      --out t1_runs/t14_mr
"""

import argparse
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from t1_whistler import (  # noqa: E402  (shared physics, identical by import)
    B0,
    BETA,
    ETA_H_STAR,
    M_ION,
    Te_eV,
    c_light,
    l_i,
    n0,
    run_warpx,
    t_ci,
    u_th,
    vA,
    w_ci,
)

# ----------------------------------------------------------------------
# grid: coarse dz = 0.5 l_i; half the T1.1 domain length
# ----------------------------------------------------------------------
DZ_COARSE_LI = 0.5
NZ_COARSE = 512
NX_COARSE = 4
dz_c = DZ_COARSE_LI * l_i
Lz = NZ_COARSE * dz_c  # = 256 l_i
Lx = NX_COARSE * dz_c  # = 2 l_i
k_Nyq_coarse = np.pi / dz_c

PATCH_ZLO_FAC, PATCH_ZHI_FAC = 0.375, 0.625  # seams at 96 and 160 l_i

INPUTS_TEMPLATE = """# auto-generated by t1_4_td.py -- do not edit ({case_name})
max_step = {steps}
warpx.const_dt = {dt:.10e}
warpx.verbose = 1

amr.n_cell = {nx} {nz}
amr.max_level = {max_level}
amr.blocking_factor = 4
amr.max_grid_size = {max_grid_size}
amr.n_error_buf = 0
{fine_tag_block}
geometry.dims = 2
geometry.prob_lo = {xlo:.10e} 0.0
geometry.prob_hi = {xhi:.10e} {Lz:.10e}

boundary.field_lo = periodic periodic
boundary.field_hi = periodic periodic
boundary.particle_lo = periodic periodic
boundary.particle_hi = periodic periodic

algo.maxwell_solver = hybrid
algo.current_deposition = direct
algo.particle_shape = 1

hybrid_pic_model.elec_temp = {Te:.10e}
hybrid_pic_model.gamma = 1.0
hybrid_pic_model.n0_ref = {n0:.10e}
hybrid_pic_model.plasma_resistivity(rho,J,t) = {eta}
hybrid_pic_model.plasma_hyper_resistivity(rho,B) = {eta_h}
hybrid_pic_model.substeps = {substeps}

# initial B: in-plane-perpendicular rotation at constant |B| (TD), Bz = 0
warpx.B_ext_grid_init_style = parse_b_ext_grid_function
warpx.Bx_external_grid_function(x,y,z) = "{bx_expr}"
warpx.By_external_grid_function(x,y,z) = "{by_expr}"
warpx.Bz_external_grid_function(x,y,z) = "0.0"

particles.species_names = ions
ions.charge = q_e
ions.mass = {M_ion:.10e}
ions.injection_style = nrandompercell
ions.num_particles_per_cell = {ppc}
ions.profile = constant
ions.density = {n0:.10e}
ions.momentum_distribution_type = gaussian
ions.ux_m = 0.0
ions.uy_m = 0.0
ions.uz_m = {uzm:.10e}
ions.ux_th = {uth:.10e}
ions.uy_th = {uth:.10e}
ions.uz_th = {uth:.10e}

diagnostics.diags_names = diag1
diag1.diag_type = Full
diag1.format = plotfile
diag1.intervals = {plot_int}
diag1.fields_to_plot = Bx By Bz Ex Ey Ez
diag1.write_species = 0

warpx.reduced_diags_names = field_energy
field_energy.type = FieldEnergy
field_energy.intervals = 10

warpx.serialize_initial_conditions = 1
"""


def build_case(args):
    if args.resolution == "coarse":
        nx, nz = NX_COARSE, NZ_COARSE
    else:  # uniform-fine reference, dz = 0.25 l_i everywhere
        nx, nz = 2 * NX_COARSE, 2 * NZ_COARSE
        assert args.max_level == 0, "fine resolution is a max_level=0 reference"
    dx = Lx / nx

    za = args.za_li * l_i
    zb = args.zb_li * l_i
    L = args.layer_li * l_i
    dth2 = 0.5 * np.deg2rad(args.dtheta_deg)
    theta = f"({dth2:.10e}*(tanh((z-{za:.10e})/{L:.10e})-tanh((z-{zb:.10e})/{L:.10e})))"
    bx_expr = f"{B0:.10e}*cos{theta}"
    by_expr = f"{B0:.10e}*sin{theta}"
    uz_drift = args.drift_va * vA

    if args.max_level > 0:
        xtlo, xthi = -0.5 * Lx - dx, +0.5 * Lx + dx  # full-x patch
        fine_tag_block = (
            f"warpx.fine_tag_lo = {xtlo:.10e} {PATCH_ZLO_FAC * Lz:.10e}\n"
            f"warpx.fine_tag_hi = {xthi:.10e} {PATCH_ZHI_FAC * Lz:.10e}\n"
        )
    else:
        fine_tag_block = ""

    dt = args.dt_fac * t_ci
    eta_h = args.eta_h_fac * ETA_H_STAR

    case = dict(
        case_name=args.name,
        steps=args.steps,
        dt=dt,
        dt_fac=args.dt_fac,
        nx=nx,
        nz=nz,
        max_grid_size=args.max_grid_size,
        max_level=args.max_level,
        resolution=args.resolution,
        xlo=-0.5 * Lx,
        xhi=+0.5 * Lx,
        Lz=Lz,
        Lx=Lx,
        fine_tag_block=fine_tag_block,
        Te=Te_eV,
        n0=n0,
        eta=args.eta,
        eta_h=f"{eta_h:.10e}" if args.eta_h_fac > 0 else "0.0",
        eta_h_fac=args.eta_h_fac,
        substeps=args.substeps,
        B0=B0,
        bx_expr=bx_expr,
        by_expr=by_expr,
        uzm=uz_drift / c_light,
        M_ion=M_ION,
        ppc=args.ppc,
        uth=u_th,
        plot_int=args.plot_int,
        # bookkeeping for the analysis
        mode="td",
        za=za,
        zb=zb,
        za_li=args.za_li,
        zb_li=args.zb_li,
        layer_L=L,
        layer_li=args.layer_li,
        dtheta_deg=args.dtheta_deg,
        drift_va=args.drift_va,
        uz_drift=uz_drift,
        patch_zlo=PATCH_ZLO_FAC * Lz,
        patch_zhi=PATCH_ZHI_FAC * Lz,
        w_ci=w_ci,
        t_ci=t_ci,
        l_i=l_i,
        vA=vA,
        k_nyq_coarse=k_Nyq_coarse,
        beta=BETA,
        dz_coarse=dz_c,
        extra_inputs=args.extra_inputs,
    )
    return case


def write_run(case, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    # named inputs_t1 because t1_whistler.run_warpx hardcodes that filename
    inputs_path = os.path.join(out_dir, "inputs_t1")
    with open(inputs_path, "w") as f:
        f.write(INPUTS_TEMPLATE.format(**case))
        for line in case.get("extra_inputs") or []:
            f.write(line + "\n")
    with open(os.path.join(out_dir, "params.json"), "w") as f:
        json.dump(
            {k: v for k, v in case.items() if not k.endswith("_block")},
            f,
            indent=1,
            default=float,
        )
    return inputs_path


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--name", default="t14_run")
    p.add_argument("--max-level", type=int, default=1, choices=[0, 1])
    p.add_argument("--resolution", choices=["coarse", "fine"], default="coarse")
    p.add_argument("--eta", default="1.0e-10", help="plasma_resistivity (Ohm m)")
    p.add_argument("--eta-h-fac", type=float, default=0.0)
    p.add_argument("--dtheta-deg", type=float, default=90.0, help="total B rotation")
    p.add_argument("--za-li", type=float, default=64.0, help="trailing layer (l_i)")
    p.add_argument("--zb-li", type=float, default=88.0, help="leading layer (l_i)")
    p.add_argument("--layer-li", type=float, default=1.5, help="layer width L (l_i)")
    p.add_argument("--drift-va", type=float, default=1.0, help="bulk u_z / vA")
    p.add_argument("--substeps", type=int, default=24)
    p.add_argument("--max-grid-size", type=int, default=64)
    p.add_argument("--extra-inputs", action="append", default=None)
    p.add_argument("--ppc", type=int, default=64)
    p.add_argument("--dt-fac", type=float, default=0.012, help="dt / t_ci")
    p.add_argument("--steps", type=int, default=1900)
    p.add_argument("--plot-int", type=int, default=5)
    p.add_argument("--out", required=True)
    p.add_argument("--exe", default=None)
    p.add_argument("--nprocs", type=int, default=8)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    if args.exe is None:
        args.exe = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "..",
            "..",
            "..",
            "build",
            "bin",
            "warpx.2d",
        )

    case = build_case(args)
    write_run(case, args.out)
    t_first = (case["patch_zlo"] - case["zb"]) / case["uz_drift"] / t_ci
    t_out = (case["patch_zhi"] - case["za"]) / case["uz_drift"] / t_ci
    print(
        f"[t1_4_td] {args.name}: dtheta = {args.dtheta_deg} deg, layers at "
        f"{args.za_li}/{args.zb_li} l_i (L = {args.layer_li} l_i), drift "
        f"{args.drift_va} vA; leading layer hits seam at {t_first:.2f} t_ci, "
        f"slab fully out at {t_out:.2f} t_ci; horizon "
        f"{args.steps * args.dt_fac:.1f} t_ci"
    )
    if args.dry_run:
        return 0
    rc = run_warpx(case, args.out, args.exe, args.nprocs)
    if rc != 0:
        print(f"[t1_4_td] WARNING: {args.name} exited with code {rc}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
