#!/usr/bin/env python3
"""T1.7 -- low-density (Holmstrom-vacuum-adjacent) seam deck for hybrid-PIC MR.

Quiet quasi-1D 2D configuration on the T1.3 grid (4 x 256 coarse cells,
dz = 0.5 l_i, Lz = 128 l_i, static ratio-2 patch over the middle quarter of
z, seams at 48 and 80 l_i), with a controlled density GAP

    n(z) = n0 * [ f + (1-f) * (1 - 0.5*(tanh((z-za)/L) - tanh((z-zb)/L))) ]

whose floor value f*n0 coincides with the hybrid solver's density floor
(hybrid_pic_model.n_floor = f*n0, f = 0.05 by default) so that PIC noise
(sigma_n/n ~ 1/sqrt(ppc) = 12.5 % at 64 ppc) makes gap cells straddle the
clamp. holmstrom_vacuum_region = 1: cells below the floor get E = 0, cells
at/above it divide the Ohm's-law numerator by max(rho, rho_floor) -- the
maximally-amplified-Hall band this test places against the patch seam.

B = B0 z everywhere (no wave): grad n is parallel to B so the exact
solution keeps B uniform (no diamagnetic current), and the T1-battery
seam-instability monitor max|Bz - B0| stays a pure noise/instability
detector. The gap is NOT pressure balanced (isothermal electrons, uniform
Ti): it fills by rarefaction on the ion-thermal timescale, which is why
the analysis defines an early window (t <= 2 t_ci) where the seam still
sits at floor conditions.

Whistler stiffness at the floor: the Hall coefficient is clamped at
1/(q n_floor), so on the FINE level omega_max ~ (k_Nc,f * l_i/sqrt(f))^2
~ 3.2e3 w_ci at f = 0.05. RK4 substep stability (|omega dt_sub| < 2.83 on
the imaginary axis) at dt = 0.012 t_ci then needs >= 85 substeps;
substeps = 192 (2.2x margin) is the deck default, applied identically to
every arm.

warpx.refine_plasma_init = 1 is written into ALL arms (measured amendment,
T1_RESULTS.md: mandatory for MR arms, byte-identical no-op at
max_level = 0).

Example:
  python t1_7_lowden.py --name t17_floor_e7_mr --max-level 1 \
      --gap-za-li 40 --gap-zb-li 56 --eta 1.0e-7 --steps 667 \
      --out t1_runs/t17_floor_e7_mr
"""

import argparse
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from t1_whistler import (  # noqa: E402  (shared physics, identical by import)
    B0,
    BETA,
    ETA_H_STAR,
    M_ION,
    Te_eV,
    l_i,
    n0,
    run_warpx,
    t_ci,
    u_th,
    vA,
    w_ci,
)

# ----------------------------------------------------------------------
# grid: identical to t1_3_alfven.py (4 x 256 coarse, dz = 0.5 l_i)
# ----------------------------------------------------------------------
DZ_COARSE_LI = 0.5
NZ_COARSE = 256
NX_COARSE = 4
dz_c = DZ_COARSE_LI * l_i
Lz = NZ_COARSE * dz_c  # = 128 l_i
Lx = NX_COARSE * dz_c  # = 2 l_i
k_Nyq_coarse = np.pi / dz_c

PATCH_ZLO_FAC, PATCH_ZHI_FAC = 0.375, 0.625  # seams at 48 and 80 l_i

INPUTS_TEMPLATE = """# auto-generated by t1_7_lowden.py -- do not edit ({case_name})
max_step = {steps}
warpx.const_dt = {dt:.10e}
warpx.verbose = 1

amr.n_cell = {nx} {nz}
amr.max_level = {max_level}
amr.blocking_factor = 4
amr.max_grid_size = {max_grid_size}
amr.n_error_buf = 0
{fine_tag_block}
geometry.dims = 2
geometry.prob_lo = {xlo:.10e} 0.0
geometry.prob_hi = {xhi:.10e} {Lz:.10e}

boundary.field_lo = periodic periodic
boundary.field_hi = periodic periodic
boundary.particle_lo = periodic periodic
boundary.particle_hi = periodic periodic

algo.maxwell_solver = hybrid
algo.current_deposition = direct
algo.particle_shape = 1

hybrid_pic_model.elec_temp = {Te:.10e}
hybrid_pic_model.gamma = 1.0
hybrid_pic_model.n0_ref = {n0:.10e}
hybrid_pic_model.plasma_resistivity(rho,J,t) = {eta}
hybrid_pic_model.plasma_hyper_resistivity(rho,B) = {eta_h}
hybrid_pic_model.substeps = {substeps}
hybrid_pic_model.n_floor = {n_floor:.10e}
hybrid_pic_model.holmstrom_vacuum_region = {holmstrom}

warpx.refine_plasma_init = 1

# initial B: uniform B0 z (no wave -- quiet low-density-seam test)
warpx.B_ext_grid_init_style = parse_b_ext_grid_function
warpx.Bx_external_grid_function(x,y,z) = "0.0"
warpx.By_external_grid_function(x,y,z) = "0.0"
warpx.Bz_external_grid_function(x,y,z) = "{B0:.10e}"

particles.species_names = ions
ions.charge = q_e
ions.mass = {M_ion:.10e}
ions.injection_style = nrandompercell
ions.num_particles_per_cell = {ppc}
ions.profile = parse_density_function
ions.density_function(x,y,z) = "{den_expr}"
ions.momentum_distribution_type = gaussian
ions.ux_th = {uth:.10e}
ions.uy_th = {uth:.10e}
ions.uz_th = {uth:.10e}

diagnostics.diags_names = diag1
diag1.diag_type = Full
diag1.format = plotfile
diag1.intervals = {plot_int}
diag1.fields_to_plot = Bx By Bz Ex Ey Ez jx jy jz rho
diag1.write_species = 0

warpx.reduced_diags_names = field_energy
field_energy.type = FieldEnergy
field_energy.intervals = 10

warpx.serialize_initial_conditions = 1
"""


def build_case(args):
    if args.resolution == "coarse":
        nx, nz = NX_COARSE, NZ_COARSE
    else:  # uniform-fine reference, dz = 0.25 l_i everywhere
        nx, nz = 2 * NX_COARSE, 2 * NZ_COARSE
        assert args.max_level == 0, "fine resolution is a max_level=0 reference"
    dx = Lx / nx

    f = args.floor_frac
    L = args.ramp_li * l_i
    if args.gap_za_li is None:  # no-gap (uniform density) baseline
        den_expr = f"{n0:.10e}"
        za = zb = None
    else:
        za = args.gap_za_li * l_i
        zb = args.gap_zb_li * l_i
        den_expr = (
            f"{n0:.10e}*({f:.6f} + {1.0 - f:.6f}*"
            f"(1.0 - 0.5*(tanh((z-{za:.10e})/{L:.10e})"
            f" - tanh((z-{zb:.10e})/{L:.10e}))))"
        )

    if args.max_level > 0:
        xtlo, xthi = -0.5 * Lx - dx, +0.5 * Lx + dx  # full-x patch
        fine_tag_block = (
            f"warpx.fine_tag_lo = {xtlo:.10e} {PATCH_ZLO_FAC * Lz:.10e}\n"
            f"warpx.fine_tag_hi = {xthi:.10e} {PATCH_ZHI_FAC * Lz:.10e}\n"
        )
    else:
        fine_tag_block = ""

    dt = args.dt_fac * t_ci
    n_floor = args.nfloor_frac * n0
    eta_h = args.eta_h_fac * ETA_H_STAR

    case = dict(
        case_name=args.name,
        steps=args.steps,
        dt=dt,
        dt_fac=args.dt_fac,
        nx=nx,
        nz=nz,
        max_grid_size=args.max_grid_size,
        max_level=args.max_level,
        resolution=args.resolution,
        xlo=-0.5 * Lx,
        xhi=+0.5 * Lx,
        Lz=Lz,
        Lx=Lx,
        fine_tag_block=fine_tag_block,
        Te=Te_eV,
        n0=n0,
        eta=args.eta,
        eta_h=f"{eta_h:.10e}" if args.eta_h_fac > 0 else "0.0",
        eta_h_fac=args.eta_h_fac,
        substeps=args.substeps,
        n_floor=n_floor,
        nfloor_frac=args.nfloor_frac,
        holmstrom=args.holmstrom,
        B0=B0,
        den_expr=den_expr,
        M_ion=M_ION,
        ppc=args.ppc,
        uth=u_th,
        plot_int=args.plot_int,
        # bookkeeping for the analysis
        mode="lowden",
        floor_frac=f,
        ramp_li=args.ramp_li,
        gap_za=za,
        gap_zb=zb,
        gap_za_li=args.gap_za_li,
        gap_zb_li=args.gap_zb_li,
        patch_zlo=PATCH_ZLO_FAC * Lz,
        patch_zhi=PATCH_ZHI_FAC * Lz,
        w_ci=w_ci,
        t_ci=t_ci,
        l_i=l_i,
        vA=vA,
        k_nyq_coarse=k_Nyq_coarse,
        beta=BETA,
        dz_coarse=dz_c,
        extra_inputs=args.extra_inputs,
    )
    return case


def write_run(case, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    inputs_path = os.path.join(out_dir, "inputs_t1")
    with open(inputs_path, "w") as fh:
        fh.write(INPUTS_TEMPLATE.format(**case))
        for line in case.get("extra_inputs") or []:
            fh.write(line + "\n")
    with open(os.path.join(out_dir, "params.json"), "w") as fh:
        json.dump(
            {k: v for k, v in case.items() if not k.endswith("_block")},
            fh,
            indent=1,
            default=float,
        )
    return inputs_path


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--name", default="t17_run")
    p.add_argument("--max-level", type=int, default=1, choices=[0, 1])
    p.add_argument("--resolution", choices=["coarse", "fine"], default="coarse")
    p.add_argument(
        "--gap-za-li", type=float, default=None, help="gap start (l_i); omit = no gap"
    )
    p.add_argument("--gap-zb-li", type=float, default=None, help="gap end (l_i)")
    p.add_argument(
        "--floor-frac",
        type=float,
        default=0.05,
        help="gap floor density / n0 (= solver n_floor by default)",
    )
    p.add_argument(
        "--nfloor-frac",
        type=float,
        default=0.05,
        help="hybrid_pic_model.n_floor / n0 (same in ALL arms)",
    )
    p.add_argument("--ramp-li", type=float, default=2.0, help="tanh ramp scale L (l_i)")
    p.add_argument("--holmstrom", type=int, default=1, choices=[0, 1])
    p.add_argument("--eta", default="1.0e-7", help="plasma_resistivity (Ohm m)")
    p.add_argument(
        "--eta-h-fac",
        type=float,
        default=0.0,
        help="hyper-resistivity in units of eta_h* = mu0 w_ci/k_Nc^4 (coarse)",
    )
    p.add_argument("--substeps", type=int, default=192)
    p.add_argument("--max-grid-size", type=int, default=32)
    p.add_argument("--extra-inputs", action="append", default=None)
    p.add_argument("--ppc", type=int, default=64)
    p.add_argument("--dt-fac", type=float, default=0.012, help="dt / t_ci")
    p.add_argument("--steps", type=int, default=667)
    p.add_argument("--plot-int", type=int, default=5)
    p.add_argument("--out", required=True)
    p.add_argument("--exe", default=None)
    p.add_argument("--nprocs", type=int, default=8)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    if (args.gap_za_li is None) != (args.gap_zb_li is None):
        p.error("--gap-za-li and --gap-zb-li must be given together")

    if args.exe is None:
        args.exe = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "..",
            "..",
            "..",
            "build",
            "bin",
            "warpx.2d",
        )

    case = build_case(args)
    write_run(case, args.out)
    gap_txt = (
        f"gap [{args.gap_za_li:g}, {args.gap_zb_li:g}] l_i"
        if args.gap_za_li is not None
        else "no gap (uniform n0)"
    )
    print(
        f"[t1_7_lowden] {args.name}: {gap_txt}, floor {args.floor_frac:g} n0, "
        f"n_floor {args.nfloor_frac:g} n0, holmstrom {args.holmstrom}, "
        f"eta {args.eta} Ohm m, substeps {args.substeps}, "
        f"horizon {args.steps * args.dt_fac:.2f} t_ci "
        f"(seams at {PATCH_ZLO_FAC * Lz / l_i:g} / {PATCH_ZHI_FAC * Lz / l_i:g} l_i)"
    )
    if args.dry_run:
        return 0
    rc = run_warpx(case, args.out, args.exe, args.nprocs)
    if rc != 0:
        print(f"[t1_7_lowden] WARNING: {args.name} exited with code {rc}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
