#!/usr/bin/env python3
"""T1 -- whistler seam-reflection deck for hybrid-PIC mesh refinement.

A.I.K.E.F.-style (Mueller et al. 2011, Fig. 8) seam test, extended past the
coarse Nyquist: quasi-1D 2D domain (thin periodic x, long periodic z),
uniform B0 along z, uniform quiet plasma (beta = 1, physics adapted from
Examples/Tests/ohm_solver_em_modes), and a right-hand circular B
perturbation
    Bx = A cos(k z),   By = -A sin(k z)
which is exactly divergence-free on the Yee mesh in 2D (Bx depends on z
only). With amr.max_level = 1 a static refinement patch (refinement ratio
2) spans the FULL x extent and the middle quarter of z, so waves launched
along z cross two z-seams and the problem stays 1D-like.

Mode types
  global : domain-wide single-k mode (T1.1, k below the coarse Nyquist)
  packet : Gaussian-envelope wave packet centered in the patch (T1.2,
           k between the coarse and fine Nyquist; the envelope +-3 sigma
           stays inside the patch interior)

The script computes the plasma parameters, writes a native WarpX inputs
file plus a params.json into --out, and (unless --dry-run) runs the
executable with mpirun. Space-time data comes from per-step PLOTFILES
(converted to npz and deleted by the battery driver): the FieldProbe
reduced diagnostic silently drops all level-0 points when amr.max_level>0
(FieldProbe.cpp clears m_data and re-gathers m_data_out once per level, so
the finest level's gather wins), which makes it unusable for this test.

Example:
  python t1_whistler.py --kfac 0.6 --mode global --max-level 1 \
      --out t1_runs/t11_k060_mr
"""

import argparse
import json
import os
import subprocess
import sys

import numpy as np

# ----------------------------------------------------------------------
# physical constants (CODATA 2018, as in WarpX)
# ----------------------------------------------------------------------
q_e = 1.602176634e-19
m_e = 9.1093837015e-31
mu0 = 1.25663706212e-06
c_light = 299792458.0

# ----------------------------------------------------------------------
# base physics (adapted from ohm_solver_em_modes parallel case, beta = 1)
# ----------------------------------------------------------------------
B0 = 0.25  # T, background field along z
M_ION = 100.0 * m_e  # ion mass
VA_OVER_C = 1.0e-4  # Alfven speed / c
BETA = 1.0  # plasma beta (Ti = Te)
AMP_FAC = 0.02  # perturbation amplitude A / B0 (linear regime)

vA = VA_OVER_C * c_light
w_ci = q_e * B0 / M_ION  # ion cyclotron angular frequency
t_ci = 2.0 * np.pi / w_ci  # ion cyclotron period
l_i = vA / w_ci  # ion skin depth
n0 = (B0 / vA) ** 2 / (mu0 * (M_ION + m_e))
v_ti = np.sqrt(BETA / 2.0) * vA
u_th = v_ti / c_light  # thermal proper velocity / c
Te_eV = M_ION * v_ti**2 / q_e  # Te = Ti (eV)

# ----------------------------------------------------------------------
# grid: coarse dz = 0.5 l_i; fine (patch or uniform-fine ref) dz = 0.25 l_i
# ----------------------------------------------------------------------
DZ_COARSE_LI = 0.5  # coarse cell size in ion skin depths
NZ_COARSE = 1024
NX_COARSE = 4
dz_c = DZ_COARSE_LI * l_i
Lz = NZ_COARSE * dz_c  # = 512 l_i
Lx = NX_COARSE * dz_c  # = 2 l_i
k_Nyq_coarse = np.pi / dz_c  # coarse Nyquist wavenumber
k_Nyq_fine = 2.0 * k_Nyq_coarse

# patch spans the middle quarter of z (multiples of blocking factor)
PATCH_ZLO_FAC, PATCH_ZHI_FAC = 0.375, 0.625

# eta_h scale: gamma_h(k) = (eta_h/mu0) k^4 = w_ci at the coarse Nyquist
ETA_H_STAR = mu0 * w_ci / k_Nyq_coarse**4

# packet envelope
SIGMA_ENV_LI = 8.0  # Gaussian envelope sigma in l_i

INPUTS_TEMPLATE = """# auto-generated by t1_whistler.py -- do not edit ({case_name})
max_step = {steps}
warpx.const_dt = {dt:.10e}
warpx.verbose = 1

amr.n_cell = {nx} {nz}
amr.max_level = {max_level}
amr.blocking_factor = 4
amr.max_grid_size = {max_grid_size}
amr.n_error_buf = 0
{fine_tag_block}
geometry.dims = 2
geometry.prob_lo = {xlo:.10e} 0.0
geometry.prob_hi = {xhi:.10e} {Lz:.10e}

boundary.field_lo = periodic periodic
boundary.field_hi = periodic periodic
boundary.particle_lo = periodic periodic
boundary.particle_hi = periodic periodic

algo.maxwell_solver = hybrid
algo.current_deposition = direct
algo.particle_shape = 1

hybrid_pic_model.elec_temp = {Te:.10e}
hybrid_pic_model.gamma = 1.0
hybrid_pic_model.n0_ref = {n0:.10e}
hybrid_pic_model.plasma_resistivity(rho,J,t) = {eta}
hybrid_pic_model.plasma_hyper_resistivity(rho,B) = {eta_h}
hybrid_pic_model.substeps = {substeps}

# initial B: uniform B0 z + right-hand circular perturbation (div-free)
warpx.B_ext_grid_init_style = parse_b_ext_grid_function
warpx.Bx_external_grid_function(x,y,z) = "{bx_expr}"
warpx.By_external_grid_function(x,y,z) = "{by_expr}"
warpx.Bz_external_grid_function(x,y,z) = "{B0:.10e}"

particles.species_names = ions
ions.charge = q_e
ions.mass = {M_ion:.10e}
ions.injection_style = nrandompercell
ions.num_particles_per_cell = {ppc}
ions.profile = constant
ions.density = {n0:.10e}
ions.momentum_distribution_type = gaussian
ions.ux_th = {uth:.10e}
ions.uy_th = {uth:.10e}
ions.uz_th = {uth:.10e}

diagnostics.diags_names = diag1
diag1.diag_type = Full
diag1.format = plotfile
diag1.intervals = {plot_int}
diag1.fields_to_plot = Bx By Bz Ex Ey Ez
diag1.write_species = 0

warpx.reduced_diags_names = field_energy
field_energy.type = FieldEnergy
field_energy.intervals = 5

warpx.serialize_initial_conditions = 1
"""


def snap_kfac(kfac):
    """Snap k = kfac * k_Nyq_coarse to a Fourier node 2*pi*m/Lz of the
    periodic domain; return (m, actual kfac, k in 1/m)."""
    m = int(round(kfac * NZ_COARSE / 2.0))
    kfac_act = 2.0 * m / NZ_COARSE
    return m, kfac_act, 2.0 * np.pi * m / Lz


def build_case(args):
    """Assemble the full parameter dict for one run."""
    m, kfac_act, k = snap_kfac(args.kfac)

    if args.resolution == "coarse":
        nx, nz = NX_COARSE, NZ_COARSE
    else:  # uniform fine reference: dz = 0.25 l_i everywhere, max_level 0
        nx, nz = 2 * NX_COARSE, 2 * NZ_COARSE
        assert args.max_level == 0, "fine resolution is a max_level=0 reference"
    dx = Lx / nx

    zc = 0.5 * Lz
    sig = SIGMA_ENV_LI * l_i
    A = args.amp_fac * B0
    if A == 0.0:
        A = 1e-30  # null (noise-only) run with an identical deck structure
    if args.mode == "global":
        bx_expr = f"{A:.10e}*cos({k:.10e}*z)"
        by_expr = f"-{A:.10e}*sin({k:.10e}*z)"
    else:  # packet centered in the patch
        env = f"exp(-(z-{zc:.10e})^2/(2*{sig:.10e}^2))"
        bx_expr = f"{A:.10e}*{env}*cos({k:.10e}*(z-{zc:.10e}))"
        by_expr = f"-{A:.10e}*{env}*sin({k:.10e}*(z-{zc:.10e}))"

    if args.max_level > 0:
        # tag every x cell (centers strictly inside the tag box) and the
        # middle quarter of z -- the patch touches both periodic x walls.
        # --patch-xfrac < 1 shrinks the patch in x (diagnostic only).
        if args.patch_xfrac >= 1.0:
            xtlo, xthi = -0.5 * Lx - dx, +0.5 * Lx + dx
        else:
            xtlo = -0.5 * args.patch_xfrac * Lx
            xthi = +0.5 * args.patch_xfrac * Lx
        ftlo = (xtlo, PATCH_ZLO_FAC * Lz)
        fthi = (xthi, PATCH_ZHI_FAC * Lz)
        fine_tag_block = (
            f"warpx.fine_tag_lo = {ftlo[0]:.10e} {ftlo[1]:.10e}\n"
            f"warpx.fine_tag_hi = {fthi[0]:.10e} {fthi[1]:.10e}\n"
        )
    else:
        fine_tag_block = ""

    eta_h = args.eta_h_fac * ETA_H_STAR
    dt = args.dt_fac * t_ci

    # line probe: M points at exactly Lz/M spacing (periodic-clean FFT);
    # M = number of FINE cells in z so the patch interior is fully sampled
    M = 2 * NZ_COARSE
    dz_pr = Lz / M

    case = dict(
        case_name=args.name,
        steps=args.steps,
        dt=dt,
        dt_fac=args.dt_fac,
        nx=nx,
        nz=nz,
        max_grid_size=args.max_grid_size,
        patch_xfrac=args.patch_xfrac,
        max_level=args.max_level,
        resolution=args.resolution,
        xlo=-0.5 * Lx,
        xhi=+0.5 * Lx,
        Lz=Lz,
        Lx=Lx,
        fine_tag_block=fine_tag_block,
        Te=Te_eV,
        n0=n0,
        eta=args.eta,
        eta_h=f"{eta_h:.10e}" if args.eta_h_fac > 0 else "0.0",
        eta_h_si=eta_h,
        eta_h_fac=args.eta_h_fac,
        substeps=args.substeps,
        B0=B0,
        bx_expr=bx_expr,
        by_expr=by_expr,
        M_ion=M_ION,
        ppc=args.ppc,
        uth=u_th,
        plot_int=args.plot_int,
        xpr=0.1 * dz_c,  # slightly off x = 0, well inside the domain
        zpr1=(M - 1) * dz_pr,
        npr=M,
        dz_probe=dz_pr,
        # bookkeeping for the analysis
        mode=args.mode,
        kfac=kfac_act,
        m_index=m,
        k_si=k,
        amp=A,
        sigma_env=sig,
        z_center=zc,
        patch_zlo=PATCH_ZLO_FAC * Lz,
        patch_zhi=PATCH_ZHI_FAC * Lz,
        w_ci=w_ci,
        t_ci=t_ci,
        l_i=l_i,
        vA=vA,
        k_nyq_coarse=k_Nyq_coarse,
        k_nyq_fine=k_Nyq_fine,
        eta_h_star=ETA_H_STAR,
        beta=BETA,
        dz_coarse=dz_c,
        extra_inputs=args.extra_inputs,
    )
    return case


def write_run(case, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    inputs_path = os.path.join(out_dir, "inputs_t1")
    with open(inputs_path, "w") as f:
        f.write(INPUTS_TEMPLATE.format(**case))
        for line in case.get("extra_inputs") or []:
            f.write(line + "\n")
    with open(os.path.join(out_dir, "params.json"), "w") as f:
        json.dump(
            {k: v for k, v in case.items() if not k.endswith("_block")},
            f,
            indent=1,
            default=float,
        )
    return inputs_path


def run_warpx(case, out_dir, exe, nprocs):
    env = dict(os.environ)
    env["OMP_NUM_THREADS"] = "1"
    cmd = [
        "mpirun",
        "-np",
        str(nprocs),
        "--bind-to",
        "none",
        os.path.abspath(exe),
        "inputs_t1",
    ]
    print(f"[t1_whistler] {case['case_name']}: {' '.join(cmd)} (in {out_dir})")
    with open(os.path.join(out_dir, "run.log"), "w") as log:
        ret = subprocess.run(
            cmd, cwd=out_dir, env=env, stdout=log, stderr=subprocess.STDOUT
        )
    return ret.returncode


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--name", default="t1_run")
    p.add_argument(
        "--kfac",
        type=float,
        required=True,
        help="k / k_Nyquist_coarse (snapped to a domain mode)",
    )
    p.add_argument("--mode", choices=["global", "packet"], default="global")
    p.add_argument("--max-level", type=int, default=1, choices=[0, 1])
    p.add_argument(
        "--resolution",
        choices=["coarse", "fine"],
        default="coarse",
        help="'fine' = uniform dz=0.25 l_i reference (max_level 0)",
    )
    p.add_argument(
        "--eta", default="1.0e-10", help="plasma_resistivity expression (Ohm m)"
    )
    p.add_argument(
        "--eta-h-fac",
        type=float,
        default=0.0,
        help="hyper-resistivity in units of eta_h* = mu0 w_ci/k_Nc^4",
    )
    p.add_argument(
        "--amp-fac",
        type=float,
        default=AMP_FAC,
        help="perturbation amplitude A/B0 (0 = null/noise-only "
        "run for coherent noise subtraction)",
    )
    p.add_argument("--substeps", type=int, default=24)
    p.add_argument(
        "--patch-xfrac",
        type=float,
        default=1.0,
        help="fraction of x covered by the patch (diagnostic)",
    )
    p.add_argument("--max-grid-size", type=int, default=64)
    p.add_argument(
        "--extra-inputs",
        action="append",
        default=None,
        help="extra raw inputs lines appended to the deck "
        "(repeatable), e.g. 'warpx.n_field_gather_buffer=0'",
    )
    p.add_argument("--ppc", type=int, default=64)
    p.add_argument("--dt-fac", type=float, default=0.012, help="dt / t_ci")
    p.add_argument("--steps", type=int, default=1250)
    p.add_argument("--plot-int", type=int, default=1)
    p.add_argument("--out", required=True)
    p.add_argument("--exe", default=None)
    p.add_argument("--nprocs", type=int, default=8)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    if args.exe is None:
        args.exe = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "..",
            "..",
            "..",
            "build",
            "bin",
            "warpx.2d",
        )

    case = build_case(args)
    write_run(case, args.out)
    print(
        f"[t1_whistler] {args.name}: kfac {case['kfac']:.4f} "
        f"(m={case['m_index']}), mode {case['mode']}, "
        f"max_level {case['max_level']}, res {case['resolution']}, "
        f"eta_h {case['eta_h']} Ohm m^3 ({case['eta_h_fac']:g} eta_h*)"
    )
    print(
        f"[t1_whistler] plasma: l_i {l_i:.4e} m, w_ci {w_ci:.4e} rad/s, "
        f"vA {vA:.4e} m/s, n0 {n0:.4e} m^-3, Te {Te_eV:.4f} eV, "
        f"dt {case['dt']:.4e} s ({args.dt_fac:g} t_ci)"
    )
    if args.dry_run:
        return 0
    rc = run_warpx(case, args.out, args.exe, args.nprocs)
    if rc != 0:
        print(f"[t1_whistler] WARNING: {args.name} exited with code {rc}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
